[package]
name = "binius_hal"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
auto_impl.workspace = true
binius_field = { path = "../field" }
binius_math = { path = "../math" }
bytemuck.workspace = true
itertools.workspace = true
rayon.workspace = true
thiserror.workspace = true
tracing.workspace = true